### ISSUE TITLE
安装不上啊！～服务器的事？

### ISSUE THREAD

**Issue by fireflycao** [DCjanus/ranger#19]
Blocking waiting for file lock on package cache lock
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to read data: The se
response
; class=Os (2)
       Fetch [                                                       ]   0.21%

**Comment by DCjanus** [comment]
这一步是需要从github拉取crates的index，如果你的网络不能访问github的话，会比较尴尬。
可行的方案是，使用[国内镜像](https://github.com/rustcc/lernaean-deploy/)

其中cargo配置文件地址为`$CARGO_HOME/config`，如果没有设置CARGO_HOME这个环境变量，则默认为`~/.cargo/config`

**Comment by DCjanus** [comment]
这一步是需要从github拉取crates的index，如果你的网络不能访问github的话，会比较尴尬。
可行的方案是，使用[国内镜像](https://github.com/rustcc/lernaean-deploy/)

其中cargo配置文件地址为`$CARGO_HOME/config`，如果没有设置CARGO_HOME这个环境变量，则默认为`~/.cargo/config`
