### ISSUE TITLE
似乎这个项目当前无法下载字幕

### ISSUE THREAD

**Issue by luis-arch** [DCjanus/ranger#88]
本人使用windows10 22h2版本。已成功编译成ranger.exe。字幕在软件是明显存在的，下载下来后使用ranger解析当下目录得到以下字幕文件:

**Comment by luis-arch** [comment]
*****.ass

<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>63DAD93D07FF7B3730DD4FC6</RequestId>
  <HostId>xlppc-subtitle.oss-cn-shanghai-internal.aliyuncs.com</HostId>
  <Key>D6/16/D6169BDE9435D33624D2403C4C93413F9975BCFC.ass</Key>
</Error>

看起来需要key才能下载了，不知作者还有意愿维护这个项目吗

**Comment by luis-arch** [comment]
得到的ass文件为：
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>63DAD93D07FF7B3730DD4FC6</RequestId>
  <HostId>xlppc-subtitle.oss-cn-shanghai-internal.aliyuncs.com</HostId>
  <Key>D6/16/D6169BDE9435D33624D2403C4C93413F9975BCFC.ass</Key>
</Error>


```

看起来这个项目当前无法下载字幕文件了，不清楚作者可有意愿继续维护该项目。

**Comment by DCjanus** [comment]
可能是迅雷已经关闭了这个 API，这个项目应该是用不了了

**Comment by luis-arch** [comment]
好的，谢谢您的回复。祝您身体健康，工作顺利。
